version: 2.1
set_environment: &set_environment
  docker:
    - image: cimg/node:12.22.9
  working_directory: ~/project
  environment:
    TZ: Asia/Tokyo
    HUSKY_SKIP_INSTALL: 1
install_hub_command: &install_hub_command
  run:
    name: Install hub command
    command: |
      curl -sSLf https://github.com/github/hub/releases/download/v2.8.3/hub-linux-amd64-2.8.3.tgz | \
      tar zxf - --strip-components=1 -C /tmp/
add_ssh_keys: &add_ssh_keys
  add_ssh_keys:
    fingerprints:
      - "SHA256:g24P04b5ccPeN5uwUbrXg9rutygZCvOWy4ay0msG0y8"
commit_and_push: &commit_and_push
  run:
    name: Commit and push
    command: |
      BASE_BREANCH=master
      HEAD_BRANCH=feature/update-fc
      git config --global user.email "tatsuya.sato@coincheck.com"
      git config --global user.name "cc-sato"
      git checkout ${BASE_BREANCH}
      git checkout -b ${HEAD_BRANCH}
      date "+%m/%d/%Y %H:%M" > README.md
      git add . && \
      git commit -m '[skip ci] build package' && \
      git push origin ${HEAD_BRANCH}
create_pull_request: &create_pull_request
  run:
    name: Create a pull request
    command: |
      HEAD_BRANCH=feature/update-fc
      PR_EXISTS=$(/tmp/bin/hub pr list --base=master --head=${HEAD_BRANCH})
      echo 'PR: '${PR_EXISTS}
      if [[ -z "$PR_EXISTS" ]]; then
        /tmp/bin/hub pull-request --message="build package" --base=${CIRCLE_PROJECT_USERNAME}:master --head=${CIRCLE_PROJECT_USERNAME}:${HEAD_BRANCH}
      fi

jobs:
  update-frontend-component-version:
    <<: *set_environment
    steps:
      - *add_ssh_keys
      - checkout
      - *install_hub_command
      - *commit_and_push
      - *create_pull_request

workflows:
  version: 2
  update-package:
    jobs:
      - update-frontend-component-version:
          filters:
            branches:
              only:
                - ci/update-fc
