name: Update Packages
on:
  repository_dispatch:
    types: [update-packages] # with client_payload.packages
  workflow_dispatch:
      packages:
        description: ''
        required: false
        default: ''

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@v1
      - name: yarn install
        # ssh接続のための接続
        env:
          PRIVATE_KEY: ${{ secrets.CI_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          yarn install
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update packages'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature/update-package
          branch-suffix: timestamp
          delete-branch: true
          title: 'Update Packages by CI'
          body: |
            @${{ github.actor }}
      - name: Check Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"