name: Update Frontend-Component Version
on:
  repository_dispatch:
    types: [update-frontend-component-version]
  workflow_dispatch:
    packages:
      description: ''
      required: false
      default: ''

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@v1
      - name: yarn install frontend-component
        run: |
          yarn add git+ssh://${{ secrets.CI_SSH_PRIVATE_KEY }}x-oauth-basic@github.com/operation-check-for-GHorganization/component
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update frontend-component'
          committer: GitHub <noreply@github.com>
          signoff: false
          author: ${{ github.actor }} <${{ github.actor }}@coincheck.com>
          branch: feature/update-package
          base: master
          delete-branch: true
          title: '【自動作成PR】masterブランチのfrontend-componentを最新Versionに'
          body: |
            https://github.com/coincheckjp/frontend-component が更新されましたので、こちらのmasterブランチも更新しましょう。
      - name: Check Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
