name: Update frontend component
on:
  repository_dispatch:
    types: [update-frontend-component]
  workflow_dispatch:
      packages:
        required: false
        default: ''

jobs:
  update-frontend-component:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: setup Node
        uses: actions/setup-node@v1
      - name: install frontend-component
        env:
          PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          yarn add git+ssh://git@github.com/operation-check-for-GHorganization/component
          eval $(ssh-agent -k)
      - name: Create Pull Request
        run: |
          curl \
            -X POST https://api.github.com/repos/operation-check-for-GHorganization/frontend/pulls \
            -H "Accept: application/vnd.github.v3+json" \
            -u ${{ secrets.REPO_ACCESS_TOKEN }} \
            -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"octocat:new-feature","base":"master"}'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commit-message: 'Update frontend-component'
          committer: GitHub <noreply@github.com>
          signoff: false
          author: ${{ github.actor }} <${{ github.actor }}@coincheck.com>
          branch: feature/update-fc
          base: master
          delete-branch: true
          title: '【自動作成PR】Update frontend-component'
          body: |
            @${{ github.actor }}
      - name: Check Pull Request
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"